In [182]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter
from itertools import combinations
from itertools import chain

In [7]:
data = pd.read_csv('movie_bd_v5.csv')
data.sample(5)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
1542,tt0433386,20000000,39143839,The Grudge 2,Sarah Michelle Gellar|Amber Tamblyn|Edison Che...,Takashi Shimizu,"What Was Once Trapped, Will Now Be Unleashed","In Tokyo, a young woman (Tamblyn) is exposed t...",102,Horror|Thriller,Columbia Pictures Corporation|Ghost House Pict...,10/13/2006,5.3,2006
942,tt0309377,50000000,26199517,Blood Work,Clint Eastwood|Jeff Daniels|Anjelica Huston|Wa...,Clint Eastwood,He's a heartbeat away from catching the killer,"Still recovering from a heart transplant, a re...",110,Crime|Drama|Mystery|Thriller,Malpaso Productions|Warner Bros. Pictures,8/4/2002,5.7,2002
1707,tt0431197,70000000,86658558,The Kingdom,Jamie Foxx|Jennifer Garner|Chris Cooper|Jason ...,Peter Berg,How do you stop an enemy who isn't afraid to die?,A team of U.S. government agents is sent to in...,110,Thriller|Action|Drama,Universal Pictures|Forward Pass|Relativity Med...,8/22/2007,6.4,2007
1415,tt0388980,25000000,15431177,The Greatest Game Ever Played,Shia LaBeouf|Stephen Dillane|Josh Flitter|Pete...,Bill Paxton,Based on a True Story,A biopic of 20-year-old Francis Ouimet who def...,120,Drama|Family,Walt Disney Pictures,9/30/2005,7.0,2005
331,tt0913354,20000000,22942221,Armored,Columbus Short|Laurence Fishburne|Skeet Ulrich...,NimrÃ³d Antal,Who will be the last man standing?,A crew of officers at an armored transport sec...,88,Action|Crime|Drama|Thriller,Screen Gems|Stars Road Entertainment|Farah Fil...,12/4/2009,5.6,2009

In [4]:
data.describe()

,budget,revenue,profit,runtime,vote_average,release_year
count,1.889000e+03,1.889000e+03,1.889000e+03,1889.000000,1889.000000,1889.000000
mean,5.431083e+07,1.553653e+08,1.010545e+08,109.658549,6.140762,2007.860773
std,4.858721e+07,2.146698e+08,1.830733e+08,18.017041,0.764763,4.468841
min,5.000000e+06,2.033165e+06,-1.657101e+08,63.000000,3.300000,2000.000000
25%,2.000000e+07,3.456058e+07,5.000000e+06,97.000000,5.600000,2004.000000
50%,3.800000e+07,8.361541e+07,4.400041e+07,107.000000,6.100000,2008.000000
75%,7.200000e+07,1.782626e+08,1.201842e+08,120.000000,6.600000,2012.000000
max,3.800000e+08,2.781506e+09,2.544506e+09,214.000000,8.100000,2015.000000

# Предобработка

In [8]:
answers = {} # создадим словарь для ответов

data.insert(3,'profit',data.revenue - data.budget) 


# тут другие ваши предобработки колонок например:

#the time given in the dataset is in string format.
#So we need to change this in datetime format
# ...

# 1. У какого фильма из списка самый большой бюджет?

Использовать варианты ответов в коде решения запрещено.    
Вы думаете и в жизни у вас будут варианты ответов?)

In [9]:
# в словарь вставляем номер вопроса и ваш ответ на него
# запишите свой вариант ответа
answers['1'] = 'Pirates of the Caribbean: On Stranger Tides (tt1298650)'
# если ответили верно, можете добавить комментарий со значком "+"

In [10]:
grouped_budget = data.groupby(['budget']).max()
display(grouped_budget.tail(1))

,imdb_id,revenue,profit,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
budget,,,,,,,,,,,,,,
380000000,tt1298650,1021683000,641683000,Pirates of the Caribbean: On Stranger Tides,Johnny Depp|PenÃ©lope Cruz|Geoffrey Rush|Ian M...,Rob Marshall,Live Forever Or Die Trying.,Captain Jack Sparrow crosses paths with a woma...,136,Adventure|Action|Fantasy,Walt Disney Pictures|Jerry Bruckheimer Films|M...,5/11/2011,6.3,2011

# 2. Какой из фильмов самый длительный (в минутах)?

In [68]:
# думаю логику работы с этим словарем вы уже поняли, 
# по этому не буду больше его дублировать
answers['2'] = 'Gods and Generals (tt0279111)'

In [69]:
grouped_runtime = data.groupby(['runtime']).max()
display(grouped_runtime.tail(1))

,imdb_id,budget,revenue,profit,original_title,cast,director,tagline,overview,genres,production_companies,release_date,vote_average,release_year
runtime,,,,,,,,,,,,,,
214,tt0279111,56000000,12923936,-43076064,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,Drama|History|War,Turner Pictures|Antietam Filmworks,2/21/2003,5.8,2003

# 3. Какой из фильмов самый короткий (в минутах)?

In [11]:
answers['3'] = 'Winnie the Pooh (tt1449283)'

In [12]:
grouped_runtime = data.groupby(['runtime']).max()
display(grouped_runtime.head(1))

,imdb_id,budget,revenue,profit,original_title,cast,director,tagline,overview,genres,production_companies,release_date,vote_average,release_year
runtime,,,,,,,,,,,,,,
63,tt1449283,30000000,14460000,-15540000,Winnie the Pooh,Jim Cummings|Travis Oates|Jim Cummings|Bud Luc...,Stephen Anderson|Don Hall,Oh Pooh.,"During an ordinary day in Hundred Acre Wood, W...",Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,4/13/2011,6.8,2011

# 4. Какова средняя длительность фильмов?

In [13]:
answers['4'] = '110'

In [14]:
data.runtime.mean()

109.6585494970884

# 5. Каково медианное значение длительности фильмов?

In [15]:
answers['5'] = '107'

In [16]:
data.describe()

,budget,revenue,profit,runtime,vote_average,release_year
count,1.889000e+03,1.889000e+03,1.889000e+03,1889.000000,1889.000000,1889.000000
mean,5.431083e+07,1.553653e+08,1.010545e+08,109.658549,6.140762,2007.860773
std,4.858721e+07,2.146698e+08,1.830733e+08,18.017041,0.764763,4.468841
min,5.000000e+06,2.033165e+06,-1.657101e+08,63.000000,3.300000,2000.000000
25%,2.000000e+07,3.456058e+07,5.000000e+06,97.000000,5.600000,2004.000000
50%,3.800000e+07,8.361541e+07,4.400041e+07,107.000000,6.100000,2008.000000
75%,7.200000e+07,1.782626e+08,1.201842e+08,120.000000,6.600000,2012.000000
max,3.800000e+08,2.781506e+09,2.544506e+09,214.000000,8.100000,2015.000000

# 6. Какой самый прибыльный фильм?
#### Внимание! Здесь и далее под «прибылью» или «убытками» понимается разность между сборами и бюджетом фильма. (прибыль = сборы - бюджет) в нашем датасете это будет (profit = revenue - budget)

In [17]:
answers['6'] = 'Avatar (tt0499549)'

In [18]:
grouped_profit = data.groupby(['profit']).max()
display(grouped_profit.tail(1))

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
profit,,,,,,,,,,,,,,
2544505847,tt0499549,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,7.1,2009

# 7. Какой фильм самый убыточный?

In [19]:
answers['7'] = 'The Lone Ranger (tt1210819)'

In [20]:
grouped_profit = data.groupby(['profit']).max()
display(grouped_profit.head(1))

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
profit,,,,,,,,,,,,,,
-165710090,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013

# 8. У скольких фильмов из датасета объем сборов оказался выше бюджета?

In [21]:
answers['8'] = '1478'

In [22]:
data[(data.revenue>data.budget)].count()

imdb_id                 1478
budget                  1478
revenue                 1478
profit                  1478
original_title          1478
cast                    1478
director                1478
tagline                 1478
overview                1478
runtime                 1478
genres                  1478
production_companies    1478
release_date            1478
vote_average            1478
release_year            1478
dtype: int64

# 9. Какой фильм оказался самым кассовым в 2008 году?

In [23]:
answers['9'] = 'The Dark Knight (tt0468569)'

In [24]:
data_2008 = data[data.release_year==2008]
grouped_profit = data_2008.groupby(['profit']).max()
grouped_profit.index[-1]

816921825

# 10. Самый убыточный фильм за период с 2012 по 2014 г. (включительно)?

In [25]:
answers['10'] = 'The Lone Ranger (tt1210819)'

In [26]:
data_12_14 = data[(data.release_year>2011) & (data.release_year<2015)]
grouped_profit = data_12_14.groupby(['profit']).max()
grouped_profit.index[0]

-165710090

# 11. Какого жанра фильмов больше всего?

In [0]:
# эту задачу тоже можно решать разными подходами, попробуй реализовать разные варианты
# если будешь добавлять функцию - выноси ее в предобработку что в начале

In [27]:
answers['11'] = 'Drama'

In [28]:
genres = data.genres.str.split('|')
genres_separate = genres.explode()
import collections
genres_count = collections.Counter()
for x in genres_separate:
    genres_count[x]+=1
genres_count

Counter({'Action': 582,
         'Adventure': 415,
         'Science Fiction': 248,
         'Thriller': 596,
         'Fantasy': 222,
         'Crime': 315,
         'Western': 19,
         'Drama': 782,
         'Family': 260,
         'Animation': 139,
         'Comedy': 683,
         'Mystery': 168,
         'Romance': 308,
         'War': 58,
         'History': 62,
         'Music': 64,
         'Horror': 176,
         'Documentary': 8,
         'Foreign': 2})

# 12. Фильмы какого жанра чаще всего становятся прибыльными?

In [29]:
answers['12'] = 'Drama'

In [30]:
genres_profit = genres_separate[data['profit']>0]
genres_profit_count = collections.Counter()
for x in genres_profit:
    genres_profit_count[x]+=1
genres_profit_count

Counter({'Action': 444,
         'Adventure': 337,
         'Science Fiction': 195,
         'Thriller': 446,
         'Fantasy': 188,
         'Crime': 231,
         'Western': 12,
         'Drama': 560,
         'Family': 226,
         'Animation': 120,
         'Comedy': 551,
         'Mystery': 119,
         'Romance': 242,
         'War': 41,
         'History': 46,
         'Music': 47,
         'Horror': 150,
         'Documentary': 7})

# 13. У какого режиссера самые большие суммарные кассовые сборы?

In [31]:
answers['13'] = 'Peter Jackson'

In [32]:
data.groupby(['director'])['revenue'].sum().sort_values(ascending = False)

director
Peter Jackson        6490593685
Christopher Nolan    4167548502
David Yates          4154295625
Michael Bay          3886938960
J.J. Abrams          3579169916
                        ...
David MichÃ´d           2295423
Steven Shainberg        2281089
Paul Schrader           2062066
Keanu Reeves            2054941
Simon Hunter            2033165
Name: revenue, Length: 957, dtype: int64

# 14. Какой режисер снял больше всего фильмов в стиле Action?

In [33]:
answers['14'] = 'Robert Rodriguez'

In [34]:
data['genres'].str.split('|', n = 1, expand = True)
action_dir = data[data['genres'] == 'Action']
action_top = action_dir.groupby(['director'])['genres'].sum().sort_values(ascending = False)
action_top

director
Rob Cohen                ActionAction
Sydney Pollack                 Action
Robert Rodriguez               Action
Rob Bowman                     Action
Ridley Scott                   Action
Renny Harlin                   Action
Paul McGuigan                  Action
Marcus Nispel                  Action
Kevin Macdonald                Action
Joseph Kahn                    Action
John Moore                     Action
Harald Zwart                   Action
Christopher McQuarrie          Action
Andy Tennant                   Action
Andrew Davis                   Action
Name: genres, dtype: object

# 15. Фильмы с каким актером принесли самые высокие кассовые сборы в 2012 году?

In [35]:
answers['15'] = 'Chris Hemsworth'

In [36]:
data2 = data[data['release_year'] == 2012].copy()
data2['actor'] = data2.cast.str.split('|')
data3 = data2.explode('actor')
data3.groupby(['actor'])['revenue'].sum().sort_values(ascending = False)

actor
Chris Hemsworth      2027450773
Denis Leary          1629460639
Anne Hathaway        1522851057
Chris Evans          1519557910
Robert Downey Jr.    1519557910
                        ...
Jason Bateman           3428048
Danny Huston            2106557
Sami Gayle              2106557
Josh Lucas              2106557
Nicolas Cage            2106557
Name: revenue, Length: 466, dtype: int64

# 16. Какой актер снялся в большем количестве высокобюджетных фильмов?

In [37]:
answers['16'] = 'Matt Damon'

In [38]:
data16 = data.copy()
data16 = data16[data.budget > data.budget.mean()]
data16.cast = data16.cast.str.split('|')
data16 = data16.explode('cast')
data16.cast.value_counts()

Matt Damon         18
Adam Sandler       17
Angelina Jolie     16
Tom Cruise         15
Eddie Murphy       15
                   ..
Isobelle Molloy     1
Diana Scarwid       1
Bill Irwin          1
Daisy Ridley        1
Dougray Scott       1
Name: cast, Length: 1505, dtype: int64

# 17. В фильмах какого жанра больше всего снимался Nicolas Cage?

In [39]:
answers['17'] = 'Action'

In [40]:
data17 = data.copy()
data17.cast = data17.cast.str.split('|')
data17.genres = data17.genres.str.split('|')
data17 = data17.explode('cast')
data17 = data17.explode('genres')
data17 = data17[data17['cast'] == 'Nicolas Cage']
data17.genres.value_counts()

Action             17
Thriller           15
Drama              12
Crime              10
Fantasy             8
Adventure           7
Comedy              6
Science Fiction     4
Animation           3
Family              3
Mystery             3
History             2
War                 1
Horror              1
Romance             1
Name: genres, dtype: int64

# 18. Самый убыточный фильм от Paramount Pictures

In [41]:
answers['18'] = 'K-19: The Widowmaker (tt0267626)'

In [42]:
data18 = data.copy()
data18.production_companies = data18.production_companies.str.split('|')
data18 = data18.explode('production_companies')
data18 = data18[data18['production_companies'] == 'Paramount Pictures']
data18.groupby(['original_title'])['profit'].sum().sort_values()

original_title
K-19: The Widowmaker                                  -64831034
Timeline                                              -60519261
Next                                                  -51788987
Alfie                                                 -46604061
Twisted                                               -24805000
                                                        ...
Mission: Impossible - Ghost Protocol                  549713380
Transformers                                          559709780
Indiana Jones and the Kingdom of the Crystal Skull    601636033
Transformers: Revenge of the Fallen                   686297228
Transformers: Dark of the Moon                        928746996
Name: profit, Length: 122, dtype: int64

# 19. Какой год стал самым успешным по суммарным кассовым сборам?

In [43]:
answers['19'] = '2015'

In [44]:
data19 = data.copy()
data19 = data19.groupby(['release_year'])['revenue'].sum()
data19

release_year
2000    10664099805
2001    13017764865
2002    14136361487
2003    14346123312
2004    15663430720
2005    15309425558
2006    14775042320
2007    18162406801
2008    18252781990
2009    20261791024
2010    21071204961
2011    22676791872
2012    23079001687
2013    23213799791
2014    23405862953
2015    25449202382
Name: revenue, dtype: int64

# 20. Какой самый прибыльный год для студии Warner Bros?

In [45]:
answers['20'] = '2014'

In [46]:
data20 = data.copy()
data20.production_companies = data20.production_companies.str.split('|')
data20 = data20.explode('production_companies')
data20 = data20[data20.production_companies.str.contains('Warner Bros')]
data20 = data20.groupby(['release_year'])['revenue'].sum().sort_values(ascending = False)
data20

release_year
2014    3246549646
2007    3183675217
2008    3050595031
2010    3008712985
2011    2845393682
2003    2814008221
2009    2737954136
2004    2731933725
2013    2599953400
2005    2412980298
2001    2280142579
2012    1869520056
2002    1702709901
2015    1691168351
2006    1576351872
2000    1025531386
Name: revenue, dtype: int64

# 21. В каком месяце за все годы суммарно вышло больше всего фильмов?

In [47]:
answers['21'] = 'Сентябрь'

In [48]:
data21 = data.copy()
data21.release_date = pd.to_datetime(data21.release_date)
data21.release_date = pd.DatetimeIndex(data21.release_date).month
data21.release_date.value_counts()

9     227
12    190
10    186
8     161
3     156
4     149
6     147
11    146
7     142
5     140
2     135
1     110
Name: release_date, dtype: int64

# 22. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)

In [49]:
answers['22'] = '429'

In [50]:
data22 = data.copy()
data22.release_date = pd.to_datetime(data22.release_date)
data22.release_date = pd.DatetimeIndex(data22.release_date).month
mounth_count = data22.release_date.value_counts()
mounth_count.sort_index(inplace=True)
mounth_summer = mounth_count[5] + mounth_count[6] + mounth_count[7]
mounth_summer

429

# 23. Для какого режиссера зима – самое продуктивное время года?

In [51]:
answers['23'] = 'Peter Jackson'

In [52]:
data23 = data.copy()
data23.release_date = pd.to_datetime(data23.release_date)
data23.release_date = pd.DatetimeIndex(data23.release_date).month
data23 = data23.query('release_date in ["12","1","2"]')
data23 = data23.groupby(['director'])['release_date'].sum().sort_values(ascending = False)
data23

director
Peter Jackson          84
Clint Eastwood         61
Steven Soderbergh      51
Nancy Meyers           48
Martin Scorsese        38
                       ..
Richard LaGravenese     1
Michael Lembeck         1
David R. Ellis          1
Renny Harlin            1
Kelly Asbury            1
Name: release_date, Length: 332, dtype: int64

# 24. Какая студия дает самые длинные названия своим фильмам по количеству символов?

In [53]:
answers['24'] = 'Four By Two Productions'

In [54]:
data24 = data.copy()
data24.insert(5,'title_len',data24.original_title.apply(lambda x: len(x))) 
data24.production_companies = data24.production_companies.str.split('|')
data24 = data24.explode('production_companies')
data24 = data24.groupby(['production_companies'])['title_len'].mean().sort_values(ascending = False)
data24

production_companies
Four By Two Productions       83.0
Jim Henson Company, The       59.0
Dos Corazones                 47.0
Museum Canada Productions     46.0
Polsky Films                  46.0
                              ...
Everest Entertainment          3.0
Berlanti Productions           3.0
XM2 Productions                2.0
Ixtlan Productions             2.0
Global Entertainment Group     2.0
Name: title_len, Length: 1771, dtype: float64

# 25. Описание фильмов какой студии в среднем самые длинные по количеству слов?

In [55]:
answers['25'] = 'Midnight Picture Show'

In [56]:
data25 = data.copy()
data25.insert(10,'overview_len',data25.overview.apply(lambda x: len(x))) 
data25.production_companies = data25.production_companies.str.split('|')
data25 = data25.explode('production_companies')
data25 = data25.groupby(['production_companies'])['overview_len'].mean().sort_values(ascending = False)
data25

production_companies
Midnight Picture Show                    1000.0
Room 9 Entertainment                      964.0
Brookwell-McNamara Entertainment          936.0
Lions Gate Family Entertainment           909.0
Crest Animation Productions               909.0
                                          ...
Projection Pictures                        74.0
London Boulevard                           74.0
Phantom Four                               72.0
Empire Pictures                            62.0
Motion Picture Corporation of America      59.0
Name: overview_len, Length: 1771, dtype: float64

# 26. Какие фильмы входят в 1 процент лучших по рейтингу?

In [58]:
answers['26'] = 'Inside Out, The Dark Knight, 12 Years a Slave'

In [58]:
data26 = data.copy()
cinema1 = np.quantile(data26.vote_average, 0.99)
data26 = data26[data26['vote_average']>cinema1]
data26

,imdb_id,budget,revenue,profit,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
9,tt2096673,175000000,853708609,678708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,Pete Docter,Meet the little voices inside your head.,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/2015,8.0,2015
34,tt3170832,6000000,35401758,29401758,Room,Brie Larson|Jacob Tremblay|Joan Allen|Sean Bri...,Lenny Abrahamson,Love knows no boundaries,Jack is a young boy of 5 years old who has liv...,117,Drama|Thriller,Element Pictures|No Trace Camping|A24|Duperele...,10/16/2015,8.0,2015
118,tt0816692,165000000,621752480,456752480,Interstellar,Matthew McConaughey|Jessica Chastain|Anne Hath...,Christopher Nolan,Mankind was born on Earth. It was never meant ...,Interstellar chronicles the adventures of a gr...,169,Adventure|Drama|Science Fiction,Paramount Pictures|Legendary Pictures|Warner B...,11/5/2014,8.0,2014
119,tt2015381,170000000,773312399,603312399,Guardians of the Galaxy,Chris Pratt|Zoe Saldana|Dave Bautista|Vin Dies...,James Gunn,All heroes start somewhere.,"Light years from Earth, 26 years after being a...",121,Action|Science Fiction|Adventure,Marvel Studios|Moving Picture Company (MPC)|Bu...,7/30/2014,7.9,2014
125,tt2084970,14000000,233555708,219555708,The Imitation Game,Benedict Cumberbatch|Keira Knightley|Matthew G...,Morten Tyldum,The true enigma was the man who cracked the code.,Based on the real life story of legendary cryp...,113,History|Drama|Thriller|War,Black Bear Pictures|Bristol Automotive,11/14/2014,8.0,2014
128,tt2267998,61000000,369330363,308330363,Gone Girl,Ben Affleck|Rosamund Pike|Carrie Coon|Neil Pat...,David Fincher,You don't know what you've got 'til it's...,With his wife's disappearance having become th...,145,Mystery|Thriller|Drama,Twentieth Century Fox Film Corporation|Regency...,10/1/2014,7.9,2014
138,tt2278388,30000000,174600318,144600318,The Grand Budapest Hotel,Ralph Fiennes|Tony Revolori|F. Murray Abraham|...,Wes Anderson,A perfect holiday without leaving home.,The Grand Budapest Hotel tells of a legendary ...,99,Comedy|Drama,Fox Searchlight Pictures|Scott Rudin Productio...,2/26/2014,7.9,2014
370,tt1375666,160000000,825500000,665500000,Inception,Leonardo DiCaprio|Joseph Gordon-Levitt|Ellen P...,Christopher Nolan,Your mind is the scene of the crime.,"Cobb, a skilled thief who commits corporate es...",148,Action|Thriller|Science Fiction|Mystery|Adventure,Legendary Pictures|Warner Bros.|Syncopy,7/14/2010,7.9,2010
599,tt0468569,185000000,1001921825,816921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008
872,tt0253474,35000000,120072577,85072577,The Pianist,Adrien Brody|Thomas Kretschmann|Frank Finlay|M...,Roman Polanski,Music was his passion. Survival was his master...,The Pianist is a film adapted from the biograp...,150,Drama|War,Bac Films|Canal+Polska|Heritage Films|Studio B...,9/24/2002,7.9,2002
1081,tt0167260,94000000,1118888979,1024888979,The Lord of the Rings: The Return of the King,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,The eye of the enemy is moving.,Aragorn is revealed as the heir to the ancient...,201,Adventure|Fantasy|Action,WingNut Films|New Line Cinema,12/1/2003,7.9,2003
1183,tt0993846,100000000,392000694,292000694,The Wolf of Wall Street,Leonardo DiCaprio|Jonah Hill|Margot Robbie|Kyl...,Martin Scorsese,EARN. SPEND. PARTY.,A New York stockbroker refuses to cooperate in...,180,Crime|Drama|Comedy,Paramount Pictures|Appian Way|EMJAG Production...,12/25/2013,7.9,2013
1191,tt2024544,20000000,187000000,167000000,12 Years a Slave,Chiwetel Ejiofor|Michael Fassbender|Lupita Nyo...,Steve McQueen,The extraordinary true story of Solomon Northup,"In the pre-Civil War United States, Solomon No...",134,Drama|History,Plan B Entertainment|Regency Enterprises|River...,10/18/2013,7.9,2013
1800,tt0209144,9000000,39723096,30723096,Memento,Guy Pearce|Carrie-Anne Moss|Joe Pantoliano|Mar...,Christopher Nolan,Some memories are best forgotten.,Suffering short-term memory loss after a head ...,113,Mystery|Thriller,Summit Entertainment|Newmarket Capital Group|T...,10/11/2000,7.9,2000

# 27. Какие актеры чаще всего снимаются в одном фильме вместе?

In [175]:
answers['27'] = 'Daniel Radcliffe & Rupert Grint'

In [181]:
data27 = data.copy()
data27.cast = data27.cast.str.split('|')
cast_pairs = []
for actors in data27.cast:
    comb = combinations(actors, 2)
    pairs = [', '.join(i) for i in comb]
    cast_pairs.append(pairs)   
cast_pairs = list(chain.from_iterable(cast_pairs))
total_pairs = Counter([item for item in sorted(cast_pairs, key=lambda x: 
                cast_pairs.count(x), reverse=True)])
total_pairs

Counter({'Daniel Radcliffe, Rupert Grint': 8,
         'Daniel Radcliffe, Emma Watson': 8,
         'Rupert Grint, Emma Watson': 7,
         'Ben Stiller, Owen Wilson': 6,
         'Johnny Depp, Helena Bonham Carter': 6,
         'Adam Sandler, Kevin James': 5,
         'Hugh Jackman, Ian McKellen': 5,
         'Kristen Stewart, Robert Pattinson': 5,
         'Kristen Stewart, Taylor Lautner': 5,
         'Robert Pattinson, Taylor Lautner': 5,
         'Jennifer Lawrence, Josh Hutcherson': 4,
         'Jennifer Lawrence, Liam Hemsworth': 4,
         'Jennifer Lawrence, Woody Harrelson': 4,
         'Josh Hutcherson, Liam Hemsworth': 4,
         'Josh Hutcherson, Woody Harrelson': 4,
         'Liam Hemsworth, Woody Harrelson': 4,
         'Tobin Bell, Costas Mandylor': 4,
         'Tobin Bell, Betsy Russell': 4,
         'Costas Mandylor, Betsy Russell': 4,
         'Vin Diesel, Jordana Brewster': 4,
         'Paul Walker, Jordana Brewster': 4,
         'Mike Myers, Eddie Murphy': 4,
         'Mike Myers, Cameron Diaz': 4,
         'Eddie Murphy, Cameron Diaz': 4,
         'Kristen Stewart, Peter Facinelli': 4,
         'Robert Pattinson, Peter Facinelli': 4,
         'Taylor Lautner, Peter Facinelli': 4,
         'George Clooney, Brad Pitt': 4,
         'Hugh Jackman, Halle Berry': 4,
         'Christian Bale, Michael Caine': 4,
         'Vin Diesel, Paul Walker': 3,
         'Vin Diesel, Michelle Rodriguez': 3,
         'Vin Diesel, Dwayne Johnson': 3,
         'Paul Walker, Michelle Rodriguez': 3,
         'Paul Walker, Dwayne Johnson': 3,
         'Robert Downey Jr., Mark Ruffalo': 3,
         'Robert Downey Jr., Scarlett Johansson': 3,
         'Chris Evans, Scarlett Johansson': 3,
         'Liam Neeson, Maggie Grace': 3,
         'Liam Neeson, Famke Janssen': 3,
         'Jennifer Lawrence, Elizabeth Banks': 3,
         'Josh Hutcherson, Elizabeth Banks': 3,
         'Liam Hemsworth, Elizabeth Banks': 3,
         'Woody Harrelson, Elizabeth Banks': 3,
         'Tom Cruise, Ving Rhames': 3,
         'Mark Wahlberg, Giovanni Ribisi': 3,
         'Johnny Depp, Paul Bettany': 3,
         'Adam Sandler, Steve Buscemi': 3,
         'Martin Freeman, Richard Armitage': 3,
         'Ian McKellen, Richard Armitage': 3,
         'Ben Stiller, Robin Williams': 3,
         'Patrick Stewart, Ian McKellen': 3,
         'Sylvester Stallone, Jason Statham': 3,
         'Sylvester Stallone, Arnold Schwarzenegger': 3,
         'Russell Crowe, Jennifer Connelly': 3,
         'Bradley Cooper, Ed Helms': 3,
         'Bradley Cooper, Zach Galifianakis': 3,
         'Bradley Cooper, Justin Bartha': 3,
         'Ed Helms, Zach Galifianakis': 3,
         'Ed Helms, Justin Bartha': 3,
         'Zach Galifianakis, Justin Bartha': 3,
         'Kristen Stewart, Ashley Greene': 3,
         'Robert Pattinson, Ashley Greene': 3,
         'Taylor Lautner, Ashley Greene': 3,
         'Bradley Cooper, Ken Jeong': 3,
         'David Cross, Justin Long': 3,
         'Jason Lee, Justin Long': 3,
         'Paul Rudd, Jason Segel': 3,
         'Shia LaBeouf, Josh Duhamel': 3,
         'Robert Downey Jr., Gwyneth Paltrow': 3,
         'Daniel Radcliffe, Ralph Fiennes': 3,
         'Emma Watson, Ralph Fiennes': 3,
         'Rupert Grint, Ralph Fiennes': 3,
         'Skandar Keynes, Georgie Henley': 3,
         'Mike Myers, Antonio Banderas': 3,
         'Mike Myers, Julie Andrews': 3,
         'Eddie Murphy, Antonio Banderas': 3,
         'Eddie Murphy, Julie Andrews': 3,
         'Cameron Diaz, Antonio Banderas': 3,
         'Cameron Diaz, Julie Andrews': 3,
         'Steve Carell, Paul Rudd': 3,
         'Elijah Wood, Ian McKellen': 3,
         'Elijah Wood, Viggo Mortensen': 3,
         'Elijah Wood, Liv Tyler': 3,
         'Elijah Wood, Orlando Bloom': 3,
         'Ian McKellen, Viggo Mortensen': 3,
         'Ian McKellen, Liv Tyler': 3,
         'Ian McKellen, Orlando Bloom': 3,
         'Viggo Mortensen, Liv Tyler': 3,
         'Viggo Mortensen, Orlando Bloom': 3,
         'Liv Tyler, Orlando Bloom': 3,
         'George Clooney, Matt Damon': 3,
         'Brad Pitt, Julia Roberts': 3,
         'Jason Biggs, Thomas Ian Nicholas': 3,
         'Jason Biggs, Seann William Scott': 3,
         'Alexa PenaVega, Daryl Sabara': 3,
         'Antonio Banderas, Carla Gugino': 3,
         'Christian Bale, Gary Oldman': 3,
         'Michael Caine, Gary Oldman': 3,
         'Daniel Craig, Judi Dench': 3,
         'Jack Black, Angelina Jolie': 3,
         'Ben Stiller, David Schwimmer': 3,
         'Ben Stiller, Chris Rock': 3,
         'Ron Perlman, John Hurt': 3,
         'Hayden Christensen, Samuel L. Jackson': 3,
         'Jason Statham, FranÃ§ois BerlÃ©and': 3,
         'John Cho, Kal Penn': 3,
         'Johnny Depp, Geoffrey Rush': 3,
         'Johnny Depp, Bill Nighy': 3,
         'Ray Romano, Denis Leary': 3,
         'John Leguizamo, Denis Leary': 3,
         'Tobey Maguire, Kirsten Dunst': 3,
         'Tobey Maguire, James Franco': 3,
         'Kirsten Dunst, James Franco': 3,
         'Tim Allen, Spencer Breslin': 3,
         'Denzel Washington, Kimberly Elise': 3,
         'Ice Cube, Mike Epps': 3,
         'Johnny Depp, Orlando Bloom': 3,
         'Johnny Depp, Keira Knightley': 3,
         'Orlando Bloom, Keira Knightley': 3,
         'Patrick Stewart, Famke Janssen': 3,
         'Hugh Jackman, Famke Janssen': 3,
         'Ian McKellen, Famke Janssen': 3,
         'Halle Berry, Famke Janssen': 3,
         'Owen Wilson, Vince Vaughn': 3,
         'Bruce Willis, Kevin Pollak': 3,
         'Shailene Woodley, Theo James': 2,
         'Shailene Woodley, Kate Winslet': 2,
         'Shailene Woodley, Ansel Elgort': 2,
         'Shailene Woodley, Miles Teller': 2,
         'Theo James, Kate Winslet': 2,
         'Theo James, Miles Teller': 2,
         'Kate Winslet, Miles Teller': 2,
         'Leonardo DiCaprio, Tom Hardy': 2,
         'Daniel Craig, Ralph Fiennes': 2,
         'Robert Downey Jr., Chris Hemsworth': 2,
         'Robert Downey Jr., Chris Evans': 2,
         'Chris Hemsworth, Scarlett Johansson': 2,
         'Mark Ruffalo, Scarlett Johansson': 2,
         'Maggie Grace, Famke Janssen': 2,
         'Dwayne Johnson, Carla Gugino': 2,
         'Christian Bale, Melissa Leo': 2,
         'Steve Carell, Ryan Gosling': 2,
         'Tom Cruise, Jeremy Renner': 2,
         'Tom Cruise, Simon Pegg': 2,
         'Jeremy Renner, Simon Pegg': 2,
         'Mark Wahlberg, Seth MacFarlane': 2,
         'Seth MacFarlane, Giovanni Ribisi': 2,
         "Dylan O'Brien, Kaya Scodelario": 2,
         'Anna Kendrick, Rebel Wilson': 2,
         'Anna Kendrick, Brittany Snow': 2,
         'Anna Kendrick, Skylar Astin': 2,
         'Liam Neeson, Boyd Holbrook': 2,
         'Edgar RamÃ\xadrez, Delroy Lindo': 2,
         'Bradley Cooper, Sienna Miller': 2,
         'Miles Teller, Michael B. Jordan': 2,
         'Rose Byrne, Bobby Cannavale': 2,
         'Hugh Jackman, Amanda Seyfried': 2,
         'Joseph Gordon-Levitt, Seth Rogen': 2,
         'Seth Rogen, Lizzy Caplan': 2,
         'Adam Sandler, Andy Samberg': 2,
         'Adam Sandler, Selena Gomez': 2,
         'Will Ferrell, Mark Wahlberg': 2,
         'Kevin James, Raini Rodriguez': 2,
         'Tina Fey, Amy Poehler': 2,
         'Tom Kenny, Bill Fagerbakke': 2,
         'Tom Kenny, Rodger Bumpass': 2,
         'Tom Kenny, Clancy Brown': 2,
         'Tom Kenny, Carolyn Lawrence': 2,
         'Bill Fagerbakke, Carolyn Lawrence': 2,
         'Rodger Bumpass, Carolyn Lawrence': 2,
         'Clancy Brown, Carolyn Lawrence': 2,
         'Chris Evans, Sebastian Stan': 2,
         'Scarlett Johansson, Samuel L. Jackson': 2,
         'Martin Freeman, Ian McKellen': 2,
         'Martin Freeman, Ken Stott': 2,
         'Martin Freeman, Graham McTavish': 2,
         'Ian McKellen, Ken Stott': 2,
         'Ian McKellen, Graham McTavish': 2,
         'Richard Armitage, Ken Stott': 2,
         'Richard Armitage, Graham McTavish': 2,
         'Ken Stott, Graham McTavish': 2,
         'Hugh Jackman, Patrick Stewart': 2,
         'James McAvoy, Patrick Stewart': 2,
         'James McAvoy, Michael Fassbender': 2,
         'Megan Fox, Will Arnett': 2,
         'Mark Wahlberg, Stanley Tucci': 2,
         'Jason Bateman, Jason Sudeikis': 2,
         'Jason Bateman, Charlie Day': 2,
         'Jason Bateman, Jennifer Aniston': 2,
         'Andrew Garfield, Emma Stone': 2,
         'James Franco, Seth Rogen': 2,
         'James Franco, Lizzy Caplan': 2,
         'Jay Baruchel, Gerard Butler': 2,
         'Jay Baruchel, Jonah Hill': 2,
         'Gerard Butler, Jonah Hill': 2,
         'Jason Statham, Arnold Schwarzenegger': 2,
         'Meryl Streep, Emily Blunt': 2,
         'Lena Headey, David Wenham': 2,
         'Jonah Hill, Dave Franco': 2,
         'Channing Tatum, Dave Franco': 2,
         'Ben Whishaw, Michael Gambon': 2,
         'Russell Crowe, Logan Lerman': 2,
         'Zac Efron, Dave Franco': 2,
         'Ryan Guzman, Stephen Boss': 2,
         'Joaquin Phoenix, Reese Witherspoon': 2,
         'Jessica Alba, Josh Brolin': 2,
         'Jessica Alba, Rosario Dawson': 2,
         'Jesse Eisenberg, Anne Hathaway': 2,
         'Jesse Eisenberg, Leslie Mann': 2,
         'Anne Hathaway, Leslie Mann': 2,
         'George Clooney, Bill Murray': 2,
         'George Clooney, John Goodman': 2,
         'Kit Harington, Carrie-Anne Moss': 2,
         'Channing Tatum, Sienna Miller': 2,
         'Zac Efron, Imogen Poots': 2,
         'Michael Ealy, Regina Hall': 2,
         'Morgan Freeman, Ashley Judd': 2,
         'Morgan Freeman, Nathan Gamble': 2,
         'Morgan Freeman, Harry Connick Jr.': 2,
         'Ashley Judd, Nathan Gamble': 2,
         'Ashley Judd, Harry Connick Jr.': 2,
         'Michael Sheen, Shane Brolly': 2,
         'Chris Pine, Zachary Quinto': 2,
         'Robert Downey Jr., Jude Law': 2,
         'John Cusack, Amanda Peet': 2,
         'Jennifer Connelly, Christopher Plummer': 2,
         'Jesse Eisenberg, Woody Harrelson': 2,
         'Kristen Stewart, Billy Burke': 2,
         'Robert Pattinson, Billy Burke': 2,
         'Bill Hader, Anna Faris': 2,
         'Bill Hader, James Caan': 2,
         'Anna Faris, James Caan': 2,
         'Susan Sarandon, Stanley Tucci': 2,
         'Jason Statham, Amy Smart': 2,
         'Jason Statham, Dwight Yoakam': 2,
         'Jason Statham, Efren Ramirez': 2,
         'Amy Smart, Dwight Yoakam': 2,
         'Amy Smart, Efren Ramirez': 2,
         'Vince Vaughn, Jon Favreau': 2,
         'Jason Bateman, Jon Favreau': 2,
         'Charlize Theron, Guy Pearce': 2,
         'Seth Rogen, Paul Rudd': 2,
         'Reese Witherspoon, Paul Rudd': 2,
         'Meryl Streep, Stanley Tucci': 2,
         'Johnny Depp, Giovanni Ribisi': 2,
         'Billy Crudup, Marion Cotillard': 2,
         'Matt Damon, Scott Bakula': 2,
         'Tobin Bell, Mark Rolston': 2,
         'Costas Mandylor, Mark Rolston': 2,
         'Betsy Russell, Mark Rolston': 2,
         'Shia LaBeouf, Megan Fox': 2,
         'Shia LaBeouf, Tyrese Gibson': 2,
         'Megan Fox, Tyrese Gibson': 2,
         'Josh Duhamel, Tyrese Gibson': 2,
         'Jeff Bridges, Kevin Spacey': 2,
         'Dwayne Johnson, Seann William Scott': 2,
         'Nicolas Cage, Eva Mendes': 2,
         'Seth Rogen, Leslie Mann': 2,
         'Naomi Watts, Armin Mueller-Stahl': 2,
         'Clive Owen, Paul Giamatti': 2,
         'Julia Roberts, Paul Giamatti': 2,
         'Jason Bateman, Kristen Wiig': 2,
         'Robert Downey Jr., Jamie Foxx': 2,
         'Michael Caine, Emily Mortimer': 2,
         'Danny Huston, Lynn Collins': 2,
         'Robert Downey Jr., Don Cheadle': 2,
         'Gwyneth Paltrow, Don Cheadle': 2,
         'Steve Carell, Russell Brand': 2,
         'Steve Carell, Will Arnett': 2,
         'Jason Segel, Russell Brand': 2,
         'Sylvester Stallone, Dolph Lundgren': 2,
         'Jason Statham, Dolph Lundgren': 2,
         'Russell Crowe, Mark Strong': 2,
         'Sam Worthington, Liam Neeson': 2,
         'Sam Worthington, Ralph Fiennes': 2,
         'Liam Neeson, Ralph Fiennes': 2,
         'Robert De Niro, Owen Wilson': 2,
         'Robert De Niro, Dustin Hoffman': 2,
         'Robert De Niro, Barbra Streisand': 2,
         'Ben Stiller, Dustin Hoffman': 2,
         'Ben Stiller, Barbra Streisand': 2,
         'Dustin Hoffman, Barbra Streisand': 2,
         'Logan Lerman, Brandon T. Jackson': 2,
         'Logan Lerman, Alexandra Daddario': 2,
         'Channing Tatum, Richard Jenkins': 2,
         'Danny Trejo, Michelle Rodriguez': 2,
         'Adam Sandler, Salma Hayek': 2,
         'Ashley Greene, Peter Facinelli': 2,
         'Brad Pitt, Jonah Hill': 2,
         'Mark Wahlberg, Dwayne Johnson': 2,
         'Helena Bonham Carter, Timothy Spall': 2,
         'Jake Gyllenhaal, Anne Hathaway': 2,
         'Tom Cruise, Cameron Diaz': 2,
         'Matt Damon, Greg Kinnear': 2,
         'Emily Blunt, Jason Segel': 2,
         'Jack Black, Amanda Peet': 2,
         'Christian Bale, Amy Adams': 2,
         'Katherine Heigl, Ashton Kutcher': 2,
         'Sarah Jessica Parker, Kristin Davis': 2,
         'Sarah Jessica Parker, Cynthia Nixon': 2,
         'Sarah Jessica Parker, Kim Cattrall': 2,
         'Sarah Jessica Parker, Chris Noth': 2,
         'Kristin Davis, Chris Noth': 2,
         'Cynthia Nixon, Chris Noth': 2,
         'Kim Cattrall, Chris Noth': 2,
         'Robert De Niro, Edward Norton': 2,
         'Zachary Gordon, Robert Capron': 2,
         'Zachary Gordon, Steve Zahn': 2,
         'Zachary Gordon, Rachael Harris': 2,
         'Robert Capron, Steve Zahn': 2,
         'Steve Zahn, Rachael Harris': 2,
         'Kristen Wiig, Maya Rudolph': 2,
         'Tyler Perry, Janet Jackson': 2,
         'Tyler Perry, Jill Scott': 2,
         'Tyler Perry, Malik Yoba': 2,
         'Janet Jackson, Malik Yoba': 2,
         'Jill Scott, Malik Yoba': 2,
         'Milla Jovovich, Ali Larter': 2,
         'John Goodman, Steve Buscemi': 2,
         'Billy Crystal, Steve Buscemi': 2,
         'RenÃ©e Zellweger, Colin Firth': 2,
         'RenÃ©e Zellweger, Hugh Grant': 2,
         'RenÃ©e Zellweger, Gemma Jones': 2,
         'RenÃ©e Zellweger, Jim Broadbent': 2,
         'Colin Firth, Gemma Jones': 2,
         'Colin Firth, Jim Broadbent': 2,
         'Hugh Grant, Gemma Jones': 2,
         'Hugh Grant, Jim Broadbent': 2,
         'George Clooney, Andy GarcÃ\xada': 2,
         'George Clooney, Julia Roberts': 2,
         'Brad Pitt, Matt Damon': 2,
         'Brad Pitt, Andy GarcÃ\xada': 2,
         'Brendan Fraser, John Hannah': 2,
         'Angelina Jolie, Noah Taylor': 2,
         'Russell Crowe, Paul Bettany': 2,
         'Jason Biggs, Chris Klein': 2,
         'Jason Biggs, Eddie Kaye Thomas': 2,
         'Seann William Scott, Eddie Kaye Thomas': 2,
         'Anne Hathaway, Julie Andrews': 2,
         'Anne Hathaway, Heather Matarazzo': 2,
         'Anne Hathaway, HÃ©ctor Elizondo': 2,
         'Julie Andrews, Heather Matarazzo': 2,
         'Julie Andrews, HÃ©ctor Elizondo': 2,
         'Ewan McGregor, Jim Broadbent': 2,
         'Johnny Depp, PenÃ©lope Cruz': 2,
         'Jude Law, Rachel Weisz': 2,
         'Heath Ledger, Shannyn Sossamon': 2,
         'Marlon Wayans, Shawn Wayans': 2,
         'Chris Tucker, Jackie Chan': 2,
         'Seth Green, Breckin Meyer': 2,
         'Breckin Meyer, Amy Smart': 2,
         'Brad Pitt, James Gandolfini': 2,
         'Anthony Hopkins, Hope Davis': 2,
         'Robert De Niro, Charlize Theron': 2,
         'DMX, Anthony Anderson': 2,
         'Mike Epps, Anna Maria Horsford': 2,
         'Jason Biggs, Amanda Detmer': 2,
         'Paul Walker, Vin Diesel': 2,
         'John Travolta, Vince Vaughn': 2,
         'Freddie Prinze Jr., Matthew Lillard': 2,
         'Cary Elwes, Joanna Lumley': 2,
         'Jack Black, Dustin Hoffman': 2,
         'Jack Black, Jackie Chan': 2,
         'Dustin Hoffman, Jackie Chan': 2,
         'Angelina Jolie, Jackie Chan': 2,
         'Colin Firth, Stellan SkarsgÃ¥rd': 2,
         'Ben Stiller, Jada Pinkett Smith': 2,
         'David Schwimmer, Chris Rock': 2,
         'Ron Perlman, Selma Blair': 2,
         'Ron Perlman, Jeffrey Tambor': 2,
         'Selma Blair, Jeffrey Tambor': 2,
         'Selma Blair, John Hurt': 2,
         'William Moseley, Anna Popplewell': 2,
         'William Moseley, Skandar Keynes': 2,
         'William Moseley, Georgie Henley': 2,
         'Anna Popplewell, Skandar Keynes': 2,
         'Anna Popplewell, Georgie Henley': 2,
         'Hugh Jackman, David Wenham': 2,
         'George Clooney, Tilda Swinton': 2,
         'George Clooney, Richard Jenkins': 2,
         'Will Ferrell, John C. Reilly': 2,
         'Will Ferrell, Mary Steenburgen': 2,
         'Seth Rogen, Danny McBride': 2,
         'James Franco, Danny McBride': 2,
         'Mark Wahlberg, Mila Kunis': 2,
         'Paul Rudd, Elizabeth Banks': 2,
         'Angelina Jolie, John Malkovich': 2,
         'John Cho, Neil Patrick Harris': 2,
         'Kal Penn, Neil Patrick Harris': 2,
         'Tobin Bell, Scott Patterson': 2,
         'Scott Patterson, Betsy Russell': 2,
         'Javier Bardem, PenÃ©lope Cruz': 2,
         'Steve Carell, Seth Rogen': 2,
         'Robert De Niro, Carla Gugino': 2,
         'Adam Sandler, John Turturro': 2,
         'Sean Penn, Josh Brolin': 2,
         'Cheryl Hines, Jeff Daniels': 2,
         'Bruce Willis, Robin Wright': 2,
         'Chris Hemsworth, Natalie Portman': 2,
         'Chris Hemsworth, Tom Hiddleston': 2,
         'Chris Hemsworth, Anthony Hopkins': 2,
         'Natalie Portman, Tom Hiddleston': 2,
         'Natalie Portman, Anthony Hopkins': 2,
         'Tom Hiddleston, Anthony Hopkins': 2,
         'Ryan Gosling, Emma Stone': 2,
         'Ryan Gosling, Marisa Tomei': 2,
         'Bradley Cooper, Robert De Niro': 2,
         'Ed Helms, Ken Jeong': 2,
         'Zach Galifianakis, Ken Jeong': 2,
         'Justin Bartha, Ken Jeong': 2,
         'Asa Butterfield, Ben Kingsley': 2,
         'Matthew McConaughey, William H. Macy': 2,
         'Jim Cummings, Bud Luckey': 2,
         'Jim Cummings, Craig Ferguson': 2,
         'Tom Hanks, Julia Roberts': 2,
         'Antonio Banderas, Salma Hayek': 2,
         'Kate Winslet, Jude Law': 2,
         'Robert De Niro, Katherine Heigl': 2,
         'Robin Williams, Johnny A. Sanchez': 2,
         'David Arquette, Neve Campbell': 2,
         'David Arquette, Courteney Cox': 2,
         'Neve Campbell, Courteney Cox': 2,
         'Devon Bostick, Rachael Harris': 2,
         'Devon Bostick, Steve Zahn': 2,
         'Jason Lee, David Cross': 2,
         'Neil Patrick Harris, Hank Azaria': 2,
         'Cate Blanchett, Tom Hollander': 2,
         'James McAvoy, Maggie Smith': 2,
         'James McAvoy, Julie Walters': 2,
         'Philip Seymour Hoffman, Marisa Tomei': 2,
         'Katie Featherston, Sprague Grayden': 2,
         'Viggo Mortensen, Vincent Cassel': 2,
         'Paul Walker, Tyrese Gibson': 2,
         'Dwayne Johnson, Jordana Brewster': 2,
         'Ray Romano, John Leguizamo': 2,
         'Matt Damon, Franka Potente': 2,
         'Matt Damon, Chris Cooper': 2,
         'Matt Damon, Brian Cox': 2,
         'Franka Potente, Brian Cox': 2,
         'Milla Jovovich, Michelle Rodriguez': 2,
         'Ewan McGregor, Natalie Portman': 2,
         'Ewan McGregor, Hayden Christensen': 2,
         'Ewan McGregor, Ian McDiarmid': 2,
         'Ewan McGregor, Samuel L. Jackson': 2,
         'Natalie Portman, Hayden Christensen': 2,
         'Natalie Portman, Ian McDiarmid': 2,
         'Natalie Portman, Samuel L. Jackson': 2,
         'Hayden Christensen, Ian McDiarmid': 2,
         'Ian McDiarmid, Samuel L. Jackson': 2,
         'Leonardo DiCaprio, Martin Sheen': 2,
         'Tom Hanks, Amy Adams': 2,
         'Adrien Brody, Thomas Kretschmann': 2,
         'Jennifer Lopez, Stanley Tucci': 2,
         'Wesley Snipes, Kris Kristofferson': 2,

# Submission

In [183]:
# в конце можно посмотреть свои ответы к каждому вопросу
answers

{'1': 'Pirates of the Caribbean: On Stranger Tides (tt1298650)',
 '3': 'Winnie the Pooh (tt1449283)',
 '4': '110',
 '5': '107',
 '6': 'Avatar (tt0499549)',
 '7': 'The Lone Ranger (tt1210819)',
 '8': '1478',
 '9': 'The Dark Knight (tt0468569)',
 '10': 'The Lone Ranger (tt1210819)',
 '11': 'Drama',
 '12': 'Drama',
 '13': 'Peter Jackson',
 '14': 'Robert Rodriguez',
 '15': 'Chris Hemsworth',
 '16': 'Matt Damon',
 '17': 'Action',
 '18': 'K-19: The Widowmaker (tt0267626)',
 '19': '2015',
 '20': '2014',
 '21': 'Сентябрь',
 '22': '429',
 '23': 'Peter Jackson',
 '24': 'Four By Two Productions',
 '25': 'Midnight Picture Show',
 '26': 'Inside Out, The Dark Knight, 12 Years a Slave',
 '27': 'Daniel Radcliffe & Rupert Grint',
 '2': 'Gods and Generals (tt0279111)'}

In [177]:
# и убедиться что ни чего не пропустил)
len(answers)

27